version: "3.3"

services:
  massa:
    image: pijee/massa-node:latest
    ports:
      - "33033:33033"
      - "33035:33035"
    volumes:
      - "./base_config:/massa/base_config/"
      - "./config:/massa/config/"
      - "./storage:/massa/storage/"