version: "3.3"

services:
  massa:
    image: pijee/massa-node:latest
    ports:
      - "31244:31244"
      - "31245:31245"
    volumes:
      - "./base_config:/massa/base_config/"
      - "./config:/massa/config/"
      - "./storage:/massa/storage/"